services:
  letterboxdwatcher:
    build: .
    container_name: letterboxdwatcher
    restart: unless-stopped
    environment:
      - DATABASE_URL=${BOTSUITE_DB_CONNECTION_STRING}
      - NOTIFICATION_ENDPOINT=${BOTSUITE_NOTIFICATION_ENDPOINT}
      - POLL_INTERVAL_MINUTES=21
      - NOTIFICATION_DELAY_SECONDS=3
      - MIN_FEED_DELAY_SECONDS=5
    networks:
      - spark

networks:
  spark:
    external: true
