services:
  letterboxdwatcher:
    build: .
    container_name: letterboxdwatcher
    restart: unless-stopped
    environment:
      - DATABASE_URL=${LETTERBOXDWATCHER_DATABASE_URL}
      - NOTIFICATION_ENDPOINT=${LETTERBOXDWATCHER_NOTIFICATION_URL}
      - POLL_INTERVAL_MINUTES=21
      - NOTIFICATION_DELAY_SECONDS=3
      - MIN_FEED_DELAY_SECONDS=5
    networks:
      - spark

networks:
  spark:
    external: true
